// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ms.Context.SqlServer;

#nullable disable

namespace ms.Migrations
{
    [DbContext(typeof(DbVFmid))]
    [Migration("20221108211259_md_busquedas")]
    partial class md_busquedas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ms.Models.VFmid.md_busquedas", b =>
                {
                    b.Property<int?>("id_busqueda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id_busqueda"), 1L, 1);

                    b.Property<string>("bloque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ide_cliente")
                        .HasColumnType("int");

                    b.Property<string>("latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("longitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tipo_interes_Id")
                        .HasColumnType("int");

                    b.Property<string>("torre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("vendedorId")
                        .HasColumnType("int");

                    b.HasKey("id_busqueda");

                    b.ToTable("md_busquedas");
                });
#pragma warning restore 612, 618
        }
    }
}
